version: '3'
services:
  web:
    build: .
    volumes:
      - ./foodgram:/var/www/html/foodgram
    ports:
      - 8081:8081
      - 3000:3000
  database:
    image: mysql:8.0
    # PDOでhostを指定するときにこのコンテナ名を使う
    container_name: mysql
    volumes:
      # データが消えてしまわないようにマウントmysqlのフォルダをマウント
      - ./mysql:/var/lib/mysql
    # MySQL8.0でのデフォルトの認証方式が「caching_sha2_password」なので変更する
    # 設定しないと "The server requested authentication method unknown to the client" とエラーになる
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # 設定必須、rootパスワード
      - MYSQL_ROOT_PASSWORD=rootpass
      # この設定はオプション、イメージの起動時に作成されるデータベース名
      - MYSQL_DATABASE=foodgramdb
